set_property PACKAGE_PIN V9   [get_ports {CLK_DIR}];                      # fmc pin B1.
set_property PACKAGE_PIN AA5  [get_ports {CLK0_M2C_N}];                   # fmc pin H5.
set_property PACKAGE_PIN Y5   [get_ports {CLK0_M2C_P}];                   # fmc pin H4.
set_property PACKAGE_PIN Y3   [get_ports {CLK1_M2C_N}];                   # fmc pin G3.
set_property PACKAGE_PIN Y4   [get_ports {CLK1_M2C_P}];                   # fmc pin G2.
set_property PACKAGE_PIN AG6  [get_ports {CLK2_BIDIR_N}];                 # fmc pin K5.
set_property PACKAGE_PIN AF6  [get_ports {CLK2_BIDIR_P}];                 # fmc pin K4.
set_property PACKAGE_PIN AF7  [get_ports {CLK3_BIDIR_N}];                 # fmc pin J3.
set_property PACKAGE_PIN AE7  [get_ports {CLK3_BIDIR_P}];                 # fmc pin J2.
set_property PACKAGE_PIN R3   [get_ports {DP0_C2M_N}];                    # fmc pin C3.
set_property PACKAGE_PIN R4   [get_ports {DP0_C2M_P}];                    # fmc pin C2.
set_property PACKAGE_PIN T1   [get_ports {DP0_M2C_N}];                    # fmc pin C7.
set_property PACKAGE_PIN T2   [get_ports {DP0_M2C_P}];                    # fmc pin C6.
set_property PACKAGE_PIN P5   [get_ports {DP1_C2M_N}];                    # fmc pin A23.
set_property PACKAGE_PIN P6   [get_ports {DP1_C2M_P}];                    # fmc pin A22.
set_property PACKAGE_PIN P1   [get_ports {DP1_M2C_N}];                    # fmc pin A3.
set_property PACKAGE_PIN P2   [get_ports {DP1_M2C_P}];                    # fmc pin A2.
set_property PACKAGE_PIN B5   [get_ports {DP10_C2M_N}];                   # fmc pin Z25.
set_property PACKAGE_PIN B6   [get_ports {DP10_C2M_P}];                   # fmc pin Z24.
set_property PACKAGE_PIN B1   [get_ports {DP10_M2C_N}];                   # fmc pin Y11.
set_property PACKAGE_PIN B2   [get_ports {DP10_M2C_P}];                   # fmc pin Y10.
set_property PACKAGE_PIN A7   [get_ports {DP11_C2M_N}];                   # fmc pin Y27.
set_property PACKAGE_PIN A8   [get_ports {DP11_C2M_P}];                   # fmc pin Y26.
set_property PACKAGE_PIN A3   [get_ports {DP11_M2C_N}];                   # fmc pin Z13.
set_property PACKAGE_PIN A4   [get_ports {DP11_M2C_P}];                   # fmc pin Z12.
set_property PACKAGE_PIN T30  [get_ports {DP12_C2M_N}];                   # fmc pin Z29.
set_property PACKAGE_PIN T29  [get_ports {DP12_C2M_P}];                   # fmc pin Z28.
set_property PACKAGE_PIN T34  [get_ports {DP12_M2C_N}];                   # fmc pin Y15.
set_property PACKAGE_PIN T33  [get_ports {DP12_M2C_P}];                   # fmc pin Y14.
set_property PACKAGE_PIN R32  [get_ports {DP13_C2M_N}];                   # fmc pin Y31.
set_property PACKAGE_PIN R31  [get_ports {DP13_C2M_P}];                   # fmc pin Y30.
set_property PACKAGE_PIN P34  [get_ports {DP13_M2C_N}];                   # fmc pin Z17.
set_property PACKAGE_PIN P33  [get_ports {DP13_M2C_P}];                   # fmc pin Z16.
set_property PACKAGE_PIN P30  [get_ports {DP14_C2M_N}];                   # fmc pin M19.
set_property PACKAGE_PIN P29  [get_ports {DP14_C2M_P}];                   # fmc pin M18.
set_property PACKAGE_PIN N32  [get_ports {DP14_M2C_N}];                   # fmc pin Y19.
set_property PACKAGE_PIN N31  [get_ports {DP14_M2C_P}];                   # fmc pin Y18.
set_property PACKAGE_PIN M30  [get_ports {DP15_C2M_N}];                   # fmc pin M23.
set_property PACKAGE_PIN M29  [get_ports {DP15_C2M_P}];                   # fmc pin M22.
set_property PACKAGE_PIN M34  [get_ports {DP15_M2C_N}];                   # fmc pin Y23.
set_property PACKAGE_PIN M33  [get_ports {DP15_M2C_P}];                   # fmc pin Y22.
set_property PACKAGE_PIN K30  [get_ports {DP16_C2M_N}];                   # fmc pin M27.
set_property PACKAGE_PIN K29  [get_ports {DP16_C2M_P}];                   # fmc pin M26.
set_property PACKAGE_PIN L32  [get_ports {DP16_M2C_N}];                   # fmc pin Z33.
set_property PACKAGE_PIN L31  [get_ports {DP16_M2C_P}];                   # fmc pin Z32.
set_property PACKAGE_PIN J32  [get_ports {DP17_C2M_N}];                   # fmc pin M31.
set_property PACKAGE_PIN J31  [get_ports {DP17_C2M_P}];                   # fmc pin M30.
set_property PACKAGE_PIN K34  [get_ports {DP17_M2C_N}];                   # fmc pin Y35.
set_property PACKAGE_PIN K33  [get_ports {DP17_M2C_P}];                   # fmc pin Y32.
set_property PACKAGE_PIN H30  [get_ports {DP18_C2M_N}];                   # fmc pin M35.
set_property PACKAGE_PIN H29  [get_ports {DP18_C2M_P}];                   # fmc pin M34.
set_property PACKAGE_PIN H34  [get_ports {DP18_M2C_N}];                   # fmc pin Z37.
set_property PACKAGE_PIN H33  [get_ports {DP18_M2C_P}];                   # fmc pin Z36.
set_property PACKAGE_PIN G32  [get_ports {DP19_C2M_N}];                   # fmc pin M39.
set_property PACKAGE_PIN G31  [get_ports {DP19_C2M_P}];                   # fmc pin M38.
set_property PACKAGE_PIN F34  [get_ports {DP19_M2C_N}];                   # fmc pin Y39.
set_property PACKAGE_PIN F33  [get_ports {DP19_M2C_P}];                   # fmc pin Y38.
set_property PACKAGE_PIN N3   [get_ports {DP2_C2M_N}];                    # fmc pin A27.
set_property PACKAGE_PIN N4   [get_ports {DP2_C2M_P}];                    # fmc pin A26.
set_property PACKAGE_PIN M1   [get_ports {DP2_M2C_N}];                    # fmc pin A7.
set_property PACKAGE_PIN M2   [get_ports {DP2_M2C_P}];                    # fmc pin A6.
set_property PACKAGE_PIN E32  [get_ports {DP20_M2C_N}];                   # fmc pin Z9.
set_property PACKAGE_PIN F30  [get_ports {DP20_M2C_N}];                   # fmc pin M15.
set_property PACKAGE_PIN E31  [get_ports {DP20_M2C_P}];                   # fmc pin Z8.
set_property PACKAGE_PIN F29  [get_ports {DP20_M2C_P}];                   # fmc pin M14.
set_property PACKAGE_PIN D34  [get_ports {DP21_C2M_N}];                   # fmc pin Y7.
set_property PACKAGE_PIN D33  [get_ports {DP21_C2M_P}];                   # fmc pin Y6.
set_property PACKAGE_PIN D30  [get_ports {DP21_M2C_N}];                   # fmc pin M11.
set_property PACKAGE_PIN D29  [get_ports {DP21_M2C_P}];                   # fmc pin M10.
set_property PACKAGE_PIN C32  [get_ports {DP22_C2M_N}];                   # fmc pin Z5.
set_property PACKAGE_PIN C31  [get_ports {DP22_C2M_P}];                   # fmc pin Z4.
set_property PACKAGE_PIN B30  [get_ports {DP22_M2C_N}];                   # fmc pin M7.
set_property PACKAGE_PIN B29  [get_ports {DP22_M2C_P}];                   # fmc pin M6.
set_property PACKAGE_PIN B34  [get_ports {DP23_C2M_N}];                   # fmc pin Y3.
set_property PACKAGE_PIN B33  [get_ports {DP23_C2M_P}];                   # fmc pin Y2.
set_property PACKAGE_PIN A32  [get_ports {DP23_M2C_N}];                   # fmc pin M3.
set_property PACKAGE_PIN A31  [get_ports {DP23_M2C_P}];                   # fmc pin M2.
set_property PACKAGE_PIN M5   [get_ports {DP3_C2M_N}];                    # fmc pin A31.
set_property PACKAGE_PIN M6   [get_ports {DP3_C2M_P}];                    # fmc pin A30.
set_property PACKAGE_PIN L3   [get_ports {DP3_M2C_N}];                    # fmc pin A11.
set_property PACKAGE_PIN L4   [get_ports {DP3_M2C_P}];                    # fmc pin A10.
set_property PACKAGE_PIN K5   [get_ports {DP4_C2M_N}];                    # fmc pin A35.
set_property PACKAGE_PIN K6   [get_ports {DP4_C2M_P}];                    # fmc pin A34.
set_property PACKAGE_PIN K1   [get_ports {DP4_M2C_N}];                    # fmc pin A15.
set_property PACKAGE_PIN K2   [get_ports {DP4_M2C_P}];                    # fmc pin A14.
set_property PACKAGE_PIN H5   [get_ports {DP5_C2M_N}];                    # fmc pin A39.
set_property PACKAGE_PIN H6   [get_ports {DP5_C2M_P}];                    # fmc pin A38.
set_property PACKAGE_PIN J3   [get_ports {DP5_M2C_N}];                    # fmc pin A19.
set_property PACKAGE_PIN J4   [get_ports {DP5_M2C_P}];                    # fmc pin A18.
set_property PACKAGE_PIN G3   [get_ports {DP6_C2M_N}];                    # fmc pin B37.
set_property PACKAGE_PIN G4   [get_ports {DP6_C2M_P}];                    # fmc pin B36.
set_property PACKAGE_PIN H1   [get_ports {DP6_M2C_N}];                    # fmc pin B17.
set_property PACKAGE_PIN H2   [get_ports {DP6_M2C_P}];                    # fmc pin B16.
set_property PACKAGE_PIN F5   [get_ports {DP7_C2M_N}];                    # fmc pin B33.
set_property PACKAGE_PIN F6   [get_ports {DP7_C2M_P}];                    # fmc pin B32.
set_property PACKAGE_PIN F1   [get_ports {DP7_M2C_N}];                    # fmc pin B13.
set_property PACKAGE_PIN F2   [get_ports {DP7_M2C_P}];                    # fmc pin B12.
set_property PACKAGE_PIN E3   [get_ports {DP8_C2M_N}];                    # fmc pin B29.
set_property PACKAGE_PIN E4   [get_ports {DP8_C2M_P}];                    # fmc pin B28.
set_property PACKAGE_PIN D1   [get_ports {DP8_M2C_N}];                    # fmc pin B9.
set_property PACKAGE_PIN D2   [get_ports {DP8_M2C_P}];                    # fmc pin B8.
set_property PACKAGE_PIN D5   [get_ports {DP9_C2M_N}];                    # fmc pin B25.
set_property PACKAGE_PIN D6   [get_ports {DP9_C2M_P}];                    # fmc pin B24.
set_property PACKAGE_PIN C3   [get_ports {DP9_M2C_N}];                    # fmc pin B5.
set_property PACKAGE_PIN C4   [get_ports {DP9_M2C_P}];                    # fmc pin B4.
set_property PACKAGE_PIN L7   [get_ports {GBTCLK0_M2C_N}];                # fmc pin D5.
set_property PACKAGE_PIN L8   [get_ports {GBTCLK0_M2C_P}];                # fmc pin D4.
set_property PACKAGE_PIN G7   [get_ports {GBTCLK1_M2C_N}];                # fmc pin B21.
set_property PACKAGE_PIN G8   [get_ports {GBTCLK1_M2C_P}];                # fmc pin B20.
set_property PACKAGE_PIN C7   [get_ports {GBTCLK2_M2C_N}];                # fmc pin L13.
set_property PACKAGE_PIN C8   [get_ports {GBTCLK2_M2C_P}];                # fmc pin L12.
set_property PACKAGE_PIN R28  [get_ports {GBTCLK3_M2C_N}];                # fmc pin L9.
set_property PACKAGE_PIN R27  [get_ports {GBTCLK3_M2C_P}];                # fmc pin L8.
set_property PACKAGE_PIN L28  [get_ports {GBTCLK4_M2C_N}];                # fmc pin L5.
set_property PACKAGE_PIN L27  [get_ports {GBTCLK4_M2C_P}];                # fmc pin L4.
set_property PACKAGE_PIN G28  [get_ports {GBTCLK5_M2C_N}];                # fmc pin Z21.
set_property PACKAGE_PIN G27  [get_ports {GBTCLK5_M2C_P}];                # fmc pin Z20.
set_property PACKAGE_PIN N11  [get_ports {HA00_N_CC}];                    # fmc pin F5.
set_property PACKAGE_PIN P11  [get_ports {HA00_P_CC}];                    # fmc pin F4.
set_property PACKAGE_PIN R8   [get_ports {HA01_N_CC}];                    # fmc pin E3.
set_property PACKAGE_PIN T8   [get_ports {HA01_P_CC}];                    # fmc pin E2.
set_property PACKAGE_PIN M14  [get_ports {HA02_N}];                       # fmc pin K8.
set_property PACKAGE_PIN M15  [get_ports {HA02_P}];                       # fmc pin K7.
set_property PACKAGE_PIN N12  [get_ports {HA03_N}];                       # fmc pin J7.
set_property PACKAGE_PIN P12  [get_ports {HA03_P}];                       # fmc pin J6.
set_property PACKAGE_PIN K15  [get_ports {HA04_N}];                       # fmc pin F8.
set_property PACKAGE_PIN L15  [get_ports {HA04_P}];                       # fmc pin F7.
set_property PACKAGE_PIN K16  [get_ports {HA05_N}];                       # fmc pin E7.
set_property PACKAGE_PIN L16  [get_ports {HA05_P}];                       # fmc pin E6.
set_property PACKAGE_PIN N8   [get_ports {HA06_N}];                       # fmc pin K11.
set_property PACKAGE_PIN N9   [get_ports {HA06_P}];                       # fmc pin K10.
set_property PACKAGE_PIN K12  [get_ports {HA07_N}];                       # fmc pin J10.
set_property PACKAGE_PIN L12  [get_ports {HA07_P}];                       # fmc pin J9.
set_property PACKAGE_PIN L11  [get_ports {HA08_N}];                       # fmc pin F11.
set_property PACKAGE_PIN M11  [get_ports {HA08_P}];                       # fmc pin F10.
set_property PACKAGE_PIN K13  [get_ports {HA09_N}];                       # fmc pin E10.
set_property PACKAGE_PIN L13  [get_ports {HA09_P}];                       # fmc pin E9.
set_property PACKAGE_PIN R13  [get_ports {HA10_N}];                       # fmc pin K14.
set_property PACKAGE_PIN T13  [get_ports {HA10_P}];                       # fmc pin K13.
set_property PACKAGE_PIN R12  [get_ports {HA11_N}];                       # fmc pin J13.
set_property PACKAGE_PIN T12  [get_ports {HA11_P}];                       # fmc pin J12.
set_property PACKAGE_PIN M13  [get_ports {HA12_N}];                       # fmc pin F14.
set_property PACKAGE_PIN N13  [get_ports {HA12_P}];                       # fmc pin F13.
set_property PACKAGE_PIN L10  [get_ports {HA13_N}];                       # fmc pin E13.
set_property PACKAGE_PIN M10  [get_ports {HA13_P}];                       # fmc pin E12.
set_property PACKAGE_PIN V11  [get_ports {HA14_N}];                       # fmc pin J16.
set_property PACKAGE_PIN V12  [get_ports {HA14_P}];                       # fmc pin J15.
set_property PACKAGE_PIN U6   [get_ports {HA15_N}];                       # fmc pin F17.
set_property PACKAGE_PIN V6   [get_ports {HA15_P}];                       # fmc pin F16.
set_property PACKAGE_PIN T6   [get_ports {HA16_N}];                       # fmc pin E16.
set_property PACKAGE_PIN T7   [get_ports {HA16_P}];                       # fmc pin E15.
set_property PACKAGE_PIN P9   [get_ports {HA17_N_CC}];                    # fmc pin K17.
set_property PACKAGE_PIN P10  [get_ports {HA17_P_CC}];                    # fmc pin K16.
set_property PACKAGE_PIN T10  [get_ports {HA18_N}];                       # fmc pin J19.
set_property PACKAGE_PIN U10  [get_ports {HA18_P}];                       # fmc pin J18.
set_property PACKAGE_PIN V7   [get_ports {HA19_N}];                       # fmc pin F20.
set_property PACKAGE_PIN V8   [get_ports {HA19_P}];                       # fmc pin F19.
set_property PACKAGE_PIN U8   [get_ports {HA20_N}];                       # fmc pin E19.
set_property PACKAGE_PIN U9   [get_ports {HA20_P}];                       # fmc pin E18.
set_property PACKAGE_PIN AC9  [get_ports {HA21_N}];                       # fmc pin K20.
set_property PACKAGE_PIN AB9  [get_ports {HA21_P}];                       # fmc pin K19.
set_property PACKAGE_PIN AA12 [get_ports {HA22_N}];                       # fmc pin J22.
set_property PACKAGE_PIN Y12  [get_ports {HA22_P}];                       # fmc pin J21.
set_property PACKAGE_PIN AC9  [get_ports {HA23_N}];                       # fmc pin K23.
set_property PACKAGE_PIN AB9  [get_ports {HA23_P}];                       # fmc pin K22.
set_property PACKAGE_PIN AL7  [get_ports {HB00_N_CC}];                    # fmc pin K26.
set_property PACKAGE_PIN AL8  [get_ports {HB00_P_CC}];                    # fmc pin K25.
set_property PACKAGE_PIN AM11 [get_ports {HB01_N}];                       # fmc pin J25.
set_property PACKAGE_PIN AL11 [get_ports {HB01_P}];                       # fmc pin J24.
set_property PACKAGE_PIN AK10 [get_ports {HB02_N}];                       # fmc pin F23.
set_property PACKAGE_PIN AJ10 [get_ports {HB02_P}];                       # fmc pin F22.
set_property PACKAGE_PIN AM10 [get_ports {HB03_N}];                       # fmc pin E22.
set_property PACKAGE_PIN AL10 [get_ports {HB03_P}];                       # fmc pin E21.
set_property PACKAGE_PIN AK9  [get_ports {HB04_N}];                       # fmc pin F26.
set_property PACKAGE_PIN AJ9  [get_ports {HB04_P}];                       # fmc pin F25.
set_property PACKAGE_PIN AM8  [get_ports {HB05_N}];                       # fmc pin E25.
set_property PACKAGE_PIN AM9  [get_ports {HB05_P}];                       # fmc pin E24.
set_property PACKAGE_PIN AL5  [get_ports {HB06_N_CC}];                    # fmc pin K29.
set_property PACKAGE_PIN AL6  [get_ports {HB06_P_CC}];                    # fmc pin K28.
set_property PACKAGE_PIN AP10 [get_ports {HB07_N}];                       # fmc pin J28.
set_property PACKAGE_PIN AP11 [get_ports {HB07_P}];                       # fmc pin J27.
set_property PACKAGE_PIN AK4  [get_ports {HB08_N}];                       # fmc pin F29.
set_property PACKAGE_PIN AK5  [get_ports {HB08_P}];                       # fmc pin F28.
set_property PACKAGE_PIN AP4  [get_ports {HB09_N}];                       # fmc pin E28.
set_property PACKAGE_PIN AP5  [get_ports {HB09_P}];                       # fmc pin E27.
set_property PACKAGE_PIN AN1  [get_ports {HB10_N}];                       # fmc pin K32.
set_property PACKAGE_PIN AM1  [get_ports {HB10_P}];                       # fmc pin K31.
set_property PACKAGE_PIN AL2  [get_ports {HB11_N}];                       # fmc pin J31.
set_property PACKAGE_PIN AL3  [get_ports {HB11_P}];                       # fmc pin J30.
set_property PACKAGE_PIN AK2  [get_ports {HB12_N}];                       # fmc pin F32.
set_property PACKAGE_PIN AK3  [get_ports {HB12_P}];                       # fmc pin F31.
set_property PACKAGE_PIN AN4  [get_ports {HB13_N}];                       # fmc pin E31.
set_property PACKAGE_PIN AM4  [get_ports {HB13_P}];                       # fmc pin E30.
set_property PACKAGE_PIN AP8  [get_ports {HB14_N}];                       # fmc pin K35.
set_property PACKAGE_PIN AN8  [get_ports {HB14_P}];                       # fmc pin K34.
set_property PACKAGE_PIN AP7  [get_ports {HB15_N}];                       # fmc pin J34.
set_property PACKAGE_PIN AN7  [get_ports {HB15_P}];                       # fmc pin J33.
set_property PACKAGE_PIN AP1  [get_ports {HB16_N}];                       # fmc pin F35.
set_property PACKAGE_PIN AM3  [get_ports {HB16_P}];                       # fmc pin F34.
set_property PACKAGE_PIN AM5  [get_ports {HB17_N_CC}];                    # fmc pin K38.
set_property PACKAGE_PIN AM6  [get_ports {HB17_P_CC}];                    # fmc pin K37.
set_property PACKAGE_PIN AP9  [get_ports {HB18_N}];                       # fmc pin J37.
set_property PACKAGE_PIN AN9  [get_ports {HB18_P}];                       # fmc pin J36.
set_property PACKAGE_PIN AL1  [get_ports {HB19_N}];                       # fmc pin E34.
set_property PACKAGE_PIN AK1  [get_ports {HB19_P}];                       # fmc pin E33.
set_property PACKAGE_PIN AP6  [get_ports {HB20_N}];                       # fmc pin F38.
set_property PACKAGE_PIN AN6  [get_ports {HB20_P}];                       # fmc pin F37.
set_property PACKAGE_PIN AP3  [get_ports {HB21_N}];                       # fmc pin E37.
set_property PACKAGE_PIN AN3  [get_ports {HB21_P}];                       # fmc pin E36.
set_property PACKAGE_PIN AA6  [get_ports {LA00_N_CC}];                    # fmc pin G7.
set_property PACKAGE_PIN AA7  [get_ports {LA00_P_CC}];                    # fmc pin G6.
set_property PACKAGE_PIN Y7   [get_ports {LA01_N_CC}];                    # fmc pin D9.
set_property PACKAGE_PIN Y8   [get_ports {LA01_P_CC}];                    # fmc pin D8.
set_property PACKAGE_PIN AC6  [get_ports {LA02_N}];                       # fmc pin H8.
set_property PACKAGE_PIN AC7  [get_ports {LA02_P}];                       # fmc pin H7.
set_property PACKAGE_PIN AC4  [get_ports {LA03_N}];                       # fmc pin G10.
set_property PACKAGE_PIN AB4  [get_ports {LA03_P}];                       # fmc pin G9.
set_property PACKAGE_PIN AC8  [get_ports {LA04_N}];                       # fmc pin H11.
set_property PACKAGE_PIN AB8  [get_ports {LA04_P}];                       # fmc pin H10.
set_property PACKAGE_PIN W4   [get_ports {LA05_N}];                       # fmc pin D12.
set_property PACKAGE_PIN W5   [get_ports {LA05_P}];                       # fmc pin D11.
set_property PACKAGE_PIN W6   [get_ports {LA06_N}];                       # fmc pin C11.
set_property PACKAGE_PIN W7   [get_ports {LA06_P}];                       # fmc pin C10.
set_property PACKAGE_PIN U4   [get_ports {LA07_N}];                       # fmc pin H14.
set_property PACKAGE_PIN U5   [get_ports {LA07_P}];                       # fmc pin H13.
set_property PACKAGE_PIN AB5  [get_ports {LA08_N}];                       # fmc pin G13.
set_property PACKAGE_PIN AB6  [get_ports {LA08_P}];                       # fmc pin G12.
set_property PACKAGE_PIN V3   [get_ports {LA09_N}];                       # fmc pin D15.
set_property PACKAGE_PIN V4   [get_ports {LA09_P}];                       # fmc pin D14.
set_property PACKAGE_PIN V1   [get_ports {LA10_N}];                       # fmc pin C15.
set_property PACKAGE_PIN V2   [get_ports {LA10_P}];                       # fmc pin C14.
set_property PACKAGE_PIN Y1   [get_ports {LA11_N}];                       # fmc pin H17.
set_property PACKAGE_PIN Y2   [get_ports {LA11_P}];                       # fmc pin H16.
set_property PACKAGE_PIN W1   [get_ports {LA12_N}];                       # fmc pin G16.
set_property PACKAGE_PIN W2   [get_ports {LA12_P}];                       # fmc pin G15.
set_property PACKAGE_PIN AA1  [get_ports {LA13_N}];                       # fmc pin D18.
set_property PACKAGE_PIN AA2  [get_ports {LA13_P}];                       # fmc pin D17.
set_property PACKAGE_PIN AC3  [get_ports {LA14_N}];                       # fmc pin C19.
set_property PACKAGE_PIN AB3  [get_ports {LA14_P}];                       # fmc pin C18.
set_property PACKAGE_PIN AC1  [get_ports {LA15_N}];                       # fmc pin H20.
set_property PACKAGE_PIN AC2  [get_ports {LA15_P}];                       # fmc pin H19.
set_property PACKAGE_PIN AD1  [get_ports {LA16_N}];                       # fmc pin G19.
set_property PACKAGE_PIN AD2  [get_ports {LA16_P}];                       # fmc pin G18.
set_property PACKAGE_PIN AF5  [get_ports {LA17_N_CC}];                    # fmc pin D21.
set_property PACKAGE_PIN AE5  [get_ports {LA17_P_CC}];                    # fmc pin D20.
set_property PACKAGE_PIN AG4  [get_ports {LA18_N_CC}];                    # fmc pin C23.
set_property PACKAGE_PIN AG5  [get_ports {LA18_P_CC}];                    # fmc pin C22.
set_property PACKAGE_PIN AE9  [get_ports {LA19_N}];                       # fmc pin H23.
set_property PACKAGE_PIN AD10 [get_ports {LA19_P}];                       # fmc pin H22.
set_property PACKAGE_PIN AF12 [get_ports {LA20_N}];                       # fmc pin G22.
set_property PACKAGE_PIN AE12 [get_ports {LA20_P}];                       # fmc pin G21.
set_property PACKAGE_PIN AH3  [get_ports {LA21_N}];                       # fmc pin H26.
set_property PACKAGE_PIN AG3  [get_ports {LA21_P}];                       # fmc pin H25.
set_property PACKAGE_PIN AG11 [get_ports {LA22_N}];                       # fmc pin G25.
set_property PACKAGE_PIN AF11 [get_ports {LA22_P}];                       # fmc pin G24.
set_property PACKAGE_PIN AH11 [get_ports {LA23_N}];                       # fmc pin D24.
set_property PACKAGE_PIN AH12 [get_ports {LA23_P}];                       # fmc pin D23.
set_property PACKAGE_PIN AJ2  [get_ports {LA24_N}];                       # fmc pin H29.
set_property PACKAGE_PIN AH2  [get_ports {LA24_P}];                       # fmc pin H28.
set_property PACKAGE_PIN AJ1  [get_ports {LA25_N}];                       # fmc pin G28.
set_property PACKAGE_PIN AH1  [get_ports {LA25_P}];                       # fmc pin G27.
set_property PACKAGE_PIN AF1  [get_ports {LA26_N}];                       # fmc pin D27.
set_property PACKAGE_PIN AF2  [get_ports {LA26_P}];                       # fmc pin D26.
set_property PACKAGE_PIN AF3  [get_ports {LA27_N}];                       # fmc pin C27.
set_property PACKAGE_PIN AE3  [get_ports {LA27_P}];                       # fmc pin C26.
set_property PACKAGE_PIN AJ5  [get_ports {LA28_N}];                       # fmc pin H32.
set_property PACKAGE_PIN AJ6  [get_ports {LA28_P}];                       # fmc pin H31.
set_property PACKAGE_PIN AJ4  [get_ports {LA29_N}];                       # fmc pin G31.
set_property PACKAGE_PIN AH4  [get_ports {LA29_P}];                       # fmc pin G30.
set_property PACKAGE_PIN AH8  [get_ports {LA30_N}];                       # fmc pin H35.
set_property PACKAGE_PIN AG8  [get_ports {LA30_P}];                       # fmc pin H34.
set_property PACKAGE_PIN AH6  [get_ports {LA31_N}];                       # fmc pin G34.
set_property PACKAGE_PIN AH7  [get_ports {LA31_P}];                       # fmc pin G33.
set_property PACKAGE_PIN AG9  [get_ports {LA32_N}];                       # fmc pin H38.
set_property PACKAGE_PIN AG10 [get_ports {LA32_P}];                       # fmc pin H37.
set_property PACKAGE_PIN AF8  [get_ports {LA33_N}];                       # fmc pin G37.
set_property PACKAGE_PIN AE8  [get_ports {LA33_P}];                       # fmc pin G36.
